name: Build Pokefirered ROM

on: [push, pull_request]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Build Dependencies
        run: |
          apt-get update
          apt-get install -y make git libpng-dev gcc

      - name: Install Missing AGBCC Compiler
        run: |
          git clone https://github.com /tmp/agbcc
          cd /tmp/agbcc
          ./build.sh
          ./install.sh /opt/devkitpro/devkitARM
      - name: Build ROM
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=/opt/devkitpro/devkitARM
          export PATH=$DEVKITARM/bin:$PATH
          make -j$(nproc)

      - name: Upload Finished GBA ROM
        uses: actions/upload-artifact@v4
        with:
          name: compiled-rom
          path: "*.gba"
